### ISSUE TITLE
Width of line string. If None in QGeometry, should it be rendered?

### ISSUE THREAD

**Issue by JeremyDrysdale-ibm** [Qiskit/qiskit-metal#103]
From @priti-ashvin-shah-ibm 

### What is the feature being requested?
Width of line string. If None in QGeometry, should it be rendered?

Why the Metal GUI would show a path with a width, when it was None in QGeometry? I would have expected the GUI to give warning that path has zero/None width. I changed GDS renderer to give warning, and GDS doesn't plot it.

From Dennis: Which path, specifically? Does this pertain to the CPWs?

From Priti: Within QGeometry there are Polygons and LineStrings. When a LineString has no width,.... talking about that.

From Zlakto: Let’s make Same as zero width.
In MPL render. And let’s render to GDS if not helper?

From Thomas: 
Ya perhaps if helper = true it is ok, though perhaps that could also just fall under a renderer option. Some of these will become clearer as we progress with the renderers I think.

**Comment by priti-ashvin-shah-ibm** [comment]
Resolved. If issues come up, we can close this.
