### ISSUE TITLE
pyEPR load bug

### ISSUE THREAD

**Issue by JeremyDrysdale-ibm** [Qiskit/qiskit-metal#104]
From @zlatko-minev 

### Information

- **Qiskit Metal version**: all
- **Python version**: all
- **Operating system**: all

### What is the current behavior?
Crash happens when importing MetalGUI only if pyEPR is imported first

### Steps to reproduce the problem
![image](https://user-images.githubusercontent.com/68995878/99472994-b7d35880-2917-11eb-86dd-1d1fd0dba6e4.png)

### What is the expected behavior?
No crash

**Comment by priti-ashvin-shah-ibm** [comment]
Has not occurred recently, also, pyepr will become stand alone and Metal will not use pyepr.
