### ISSUE TITLE
Utility_functions content removal

### ISSUE THREAD

**Issue by JeremyDrysdale-ibm** [Qiskit/qiskit-metal#106]
### What is the feature being requested?
There are some traceback functions in toolbox_python.utility_functions which don't seem to belong in metal, and aren't used elsewhere. The traceback functions do seem pretty useful, but probably belong on your local machine or in a personal repo rather than project repo. Since all the code is in a debugging state, I agree it probably doesn't make sense to delete these lines now. This issue can just be a reminder when it's getting ready to go public.

- enable_warning_traceback
- get_traceback
- print_traceback_easy

**Comment by priti-ashvin-shah-ibm** [comment]
This is open source, if someone wants to remove this they can on their local repo. Will close this.
