### ISSUE TITLE
Save / Load design

### ISSUE THREAD

**Issue by JeremyDrysdale-ibm** [Qiskit/qiskit-metal#12]
From @zlatko-minev

### What is the feature being requested?
Need to implement metal save / load functionality.

Some pickle code was written as a placeholder but not everything is pickling.

### What are use cases for this feature?
Users can save / load metal designs

**Comment by hasanakalin** [comment]
the save option is not working right now. how can I fixed with this problem?
![errtJPG](https://user-images.githubusercontent.com/37351958/112292376-16338d80-8ca2-11eb-99ba-a395eb7612d5.JPG)

**Comment by priti-ashvin-shah-ibm** [comment]
The segv happened when executing gui.edit_component('Q1') or  guit.edit_component_source('Q1').  @grace-harper-ibm , Do you have any thoughts?  

@hasanakalin  Regarding your cell that segv'd, I can't see the whole notebook.  Have you already added a component that has the name of 'Q1'? 

@hasanakalin , if your goal is to edit a component in a notebook, you can do it directly in QDesign API methods.  You don't have to use the gui methods.  There are examples in notebooks in the directory tutorials.  The notebook at `/1 High Level Demo/1.1 High Level Demo of Qiskit Metal.ipynb` shows how you can edit the options when adding a QComponent to QDesign and after it has been added to QDesign.

**Comment by priti-ashvin-shah-ibm** [comment]
@hasanakalin I am moving your question and my response  to the #metal slack channel. You question is most likely not connected to this issue.

**Comment by marcolincs** [comment]
Hi, @priti-ashvin-shah-ibm , I get that same error anytime I push on the save button in the gui (After creating a design). I thought this was a known issue and suggested this would be posted to this case #12. Sounds like it might not be a known issue?

**Comment by priti-ashvin-shah-ibm** [comment]
> Hi, @priti-ashvin-shah-ibm , I get that same error anytime I push on the save button in the gui (After creating a design). I thought this was a known issue and suggested this would be posted to this case #12. Sounds like it might not be a known issue?

Since #12 exists, it is a known issue.

**Comment by JeremyDrysdale-ibm** [comment]
Closing this in favor of
- https://github.com/Qiskit/qiskit-metal/issues/566
- https://github.com/Qiskit/qiskit-metal/issues/606
