### ISSUE TITLE
Get more participations, when options scanned

### ISSUE THREAD

**Issue by priti-ashvin-shah-ibm** [Qiskit/qiskit-metal#186]
### What is the feature being requested?
Part of breakup of #175.

Get more participations, when options scanned. 
May need Dennis, May need addition to pyepr.

### What are use cases for this feature?
Help users to do ananlysis on Metal QComponents.

**Comment by JeremyDrysdale-ibm** [comment]
Closing - open a new issue when we know what we want to do.
