### ISSUE TITLE
Release of Ansys client in Q3D and HFSS Renderers

### ISSUE THREAD

**Issue by warrench** [Qiskit/qiskit-metal#198]
### Information

- **Qiskit Metal version**: 
- **Python version**: 3.7.8
- **Operating system**: Windows

### What is the current behavior?

No functionality to disconnect from HFSS or Q3D at the renderer level. Release is handled in the pinfo from pyEPR and only for Ansys renderers. This causes Ansys to not be able to close except through the task manager.

### Steps to reproduce the problem

Create a project in HFSS or Q3D using
`q3d = design.renderers.q3d` or `hfss = design.renderers.hfss`

Open a connection to Ansys using

`q3d.open_ansys_design()` or `hfss.open_ansys_design()`

Try to close Ansys manually once a connection is successfully established.

There are no high level commands to terminate this connection at the level of the renderer.

The HFSS project can be closed with `hfss.pinfo.disconnect()` which is built into pyEPR, but performing such on a Q3D project results in an error saying that there is no HFSS session added. This is due to an assert clause in the disconnect function of pyEPR requiring an HFSS setup to be connected to.

### What is the expected behavior?

The renderer for both HFSS and Q3D should have a function to close the connection to a project and release it for the user.

### Suggested solutions

The connection to the Ansys server could be moved up in the hierarchy to the Ansys renderer, or add a change to pyEPR to better handle the deliniation between HFSS and Q3D

**Comment by marcolincs** [comment]
There does not seem to be an easy way to do this. Current plan is to wait for the conversion to the official Ansys pyAEDT library and see if the problem goes away.
@warrench , any thoughts/preferences?

**Comment by priti-ashvin-shah-ibm** [comment]
We are working on the pyaedt renderers.  This problem goes away for Ansys when we switch to pyaedt renderers.
