### ISSUE TITLE
Review Ansys Q3D analysis and HFSS eigenmode analysis and find pain points, missing improvements, things to smooth, revise, features needed

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/qiskit-metal#205]
### What is the feature being requested?
Review Ansys Q3D analysis and HFSS eigenmode analysis and find paint points, missing improvements, things to smooth, revise, features needed

Document as features in issues. 

@marcolincs  you can go over this with Dennis and Thomas and over the tutorial we are making with Dennis now for Thursday. 
We need to smooth and automate the flow 

Goal of this is to mark issues to do for a next scrum

**Comment by marcolincs** [comment]
Several issues created. Last but not least #255 . We shall close this case, and just make it a habit for us to loop on this stuff periodically.
Cheers
