### ISSUE TITLE
Gui double click on component to zoom on it

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/qiskit-metal#211]
### Information
When you double click component in the Widget below or a selection of components zoom in on it/them. 
I wrote this already but it seems to not work now. 
There is also the buttom on the top right to do this too. 
![image](https://user-images.githubusercontent.com/15937254/105112265-aa118f00-5a90-11eb-99f9-551385c77fff.png)

- **Qiskit Metal version**:
- **Python version**:
- **Operating system**:

**Comment by priti-ashvin-shah-ibm** [comment]
Same as #37 So will close this one.
