### ISSUE TITLE
Metal / Ansys renderer wire bonds

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/qiskit-metal#224]
### What is the feature being requested?

See what i did in v0.1. Need to add wirebonds every x mm along CPW paths for long CPWs. Relly only needed in EM sims, but can also be larger part of metal. Needed fro eigenmode and Z analysis. 

Tagging:
@marcolincs  for cpw knowledge and architecture decision and 
@dwang429 for ansys hfss renderer 
find help/main developer for this as needed

**Comment by ThomasGM4** [comment]
In Progress

**Comment by zlatko-minev** [comment]
Great work!

**Comment by auratrifire** [comment]
Are the wirebonds here to make sure that the CPW ground is common along the entire meander?
