### ISSUE TITLE
Qt style sheet - checkboxes for GDS/HFSS/Q3D renderers

### ISSUE THREAD

**Issue by dwang429** [Qiskit/qiskit-metal#244]
When the GDS, HFSS, and Q3D renderer windows are opened via the Metal GUI, checkboxes are visible on Macs but not Windows machines in Metal dark mode (standard view and QDark are fine). This is either a style sheet or palette issue, or both. It is particularly important for Ansys users since Ansys only works on Windows.

Testing on the Q3D and HFSS renderers has shown that the checkboxes are functional behind the scenes - in other words, when you deselect all components in the Metal design and then click in the space to the left of a select few, the followup window does indeed show endcap options only for those components selected, even if said selection cannot be verified in the first window.

![Windows_Checkboxes](https://user-images.githubusercontent.com/16978018/105930947-35de6a80-5fff-11eb-98b7-341b4484e874.png)

**Comment by JeremyDrysdale-ibm** [comment]
Closing in favor of https://github.com/Qiskit/qiskit-metal/issues/590
