### ISSUE TITLE
Exception raised when qdarkstyle is not installed

### ISSUE THREAD

**Issue by wshanks** [Qiskit/qiskit-metal#245]
It looks like this code is intended to make qdarkstyle optional by catching the import error exception, but then it calls `qdarkstyle.load_stylesheet()` any way:

https://github.com/Qiskit/qiskit-metal/blob/171fa3c0fa5309c89ad6b93ef21f3dd9c6eeb758/qiskit_metal/_gui/main_window_base.py#L525-L535

**Comment by priti-ashvin-shah-ibm** [comment]
qdarkstyle is a dependency which now is within environment.yml.

We an close this.
