### ISSUE TITLE
renderer.disconnect_ansys() needs to work all the time

### ISSUE THREAD

**Issue by marcolincs** [Qiskit/qiskit-metal#274]
### Information
- **Python version**: 3.7.8
- **Operating system**: Windows

### What is the current behavior?
fourq_q3d.disconnect_ansys() only works after some analysis has run in Ansys. It does `not` work right after having connected to Ansys, nor after having added a project or a design to Ansys.

### What is the expected behavior?
Should work all the time.

### Suggested solutions
Need to purify the meaning of "connect" and "disconnect", so that we can do independently of all the other information related to Ansys. This might require update in pyEPR (or maybe just picking  a different method).

Note: this is important because without a "disconnect" the Ansys session remains hanging, as mentioned in #198

**Comment by priti-ashvin-shah-ibm** [comment]
Future renderer using pyaedt addresses this.
