### ISSUE TITLE
PyEPR imports attrdict which deprecates in Python 3.9 

### ISSUE THREAD

**Issue by grace-harper-ibm** [Qiskit/qiskit-metal#278]
### Information

- **Qiskit Metal version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

![Screen Shot 2021-02-08 at 3 59 17 PM](https://user-images.githubusercontent.com/74260313/107286931-da60a380-6a26-11eb-83bb-9aa0c13a6448.png)

### Steps to reproduce the problem
Instantiate a TransmonPocket 

### What is the expected behavior?
No Error 

### Suggested solutions
I think this issue occurs in part because pyEPR includes `attrdict` library. 
Maybe open pyEPR to allow for later `attrdict` if possible 
![Screen Shot 2021-02-08 at 3 59 42 PM](https://user-images.githubusercontent.com/74260313/107287001-f5cbae80-6a26-11eb-8747-0f141d13a48c.png)

**Comment by zlatko-minev** [comment]
Not on my end

**Comment by priti-ashvin-shah-ibm** [comment]
This has been addressed by @GyeonghunKim  and issue should be closed.
