### ISSUE TITLE
BBQ (impedance) - 1. Set up simulation with port and lumped BC

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/qiskit-metal#292]
### What is the feature being requested?

Implement BBQ recipe for model - ask Sal, Thomas, Zlatko 
Need both port and inductance side by side to get 
![image](https://user-images.githubusercontent.com/15937254/108300667-bca1e580-716e-11eb-909f-080e20d55fe0.png)

https://arxiv.org/pdf/1204.0587.pdf

**Comment by JeremyDrysdale-ibm** [comment]
Hanhee clarified that BBQ only works on a single qubit, and thinks EPR does that better.  Moving to backlog.
