### ISSUE TITLE
BBQ (impedance) - 2. Fit Y curves

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/qiskit-metal#293]
### What is the feature being requested?
Extract splote of Y curves for BBQ 
leverage existing code if possible 
https://arxiv.org/pdf/1204.0587.pdf
![image](https://user-images.githubusercontent.com/15937254/108300716-d4796980-716e-11eb-9307-8871900372c4.png)

**Comment by grace-harper-ibm** [comment]
<img width="1077" alt="Screen Shot 2021-03-21 at 7 24 42 PM" src="https://user-images.githubusercontent.com/74260313/111926517-1867d300-8a7b-11eb-8314-1b3e1fe2be2d.png">

Can I use the above to calculate the dimensionless bosonic annihilation (creation)
operator `a_p` and then just dagger it? 
(https://physics.stackexchange.com/questions/261637/are-quantum-operators-dimensionless)

**Comment by JeremyDrysdale-ibm** [comment]
Hanhee clarified that BBQ only works on a single qubit, and thinks EPR does that better.  Moving to backlog.
