### ISSUE TITLE
BBQ (impedance) - 3. Y FITS TO ZPF

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/qiskit-metal#294]
### What is the feature being requested?
https://arxiv.org/pdf/1204.0587.pdf
![image](https://user-images.githubusercontent.com/15937254/108300774-f2df6500-716e-11eb-91e8-a1633bc1a877.png)

**Comment by JeremyDrysdale-ibm** [comment]
Hanhee clarified that BBQ only works on a single qubit, and thinks EPR does that better.  Moving to backlog.
