### ISSUE TITLE
BBQ (impedance) - 4. Use EPR Numerical diagonalization and Hamiltonian construction with BBQ ZPFs

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/qiskit-metal#295]
### What is the feature being requested?

Construct hamiltonian extract eigenvalues 
kerrs 
freqs, etc. 
improve abstraction of analysis

https://arxiv.org/pdf/1204.0587.pdf

**Comment by JeremyDrysdale-ibm** [comment]
Hanhee clarified that BBQ only works on a single qubit, and thinks EPR does that better.  Moving to backlog.
