### ISSUE TITLE
Add linting and formatting check to CI pipeline

### ISSUE THREAD

**Issue by JeremyDrysdale-ibm** [Qiskit/qiskit-metal#31]
From @coruscating 

### What is the feature being requested?
As per group meeting discussion, we should add pylint and yapf google style checks to our current CI pipeline.

### What are use cases for this feature?
Code will be checked for lint and format violations by CI automatically

**Comment by obrienpja** [comment]
The work by @ismirlia in Pull Request #787 closes this issue.
