### ISSUE TITLE
Simple tutorial: Lumped Resonator Capacitive (Resonator)

### ISSUE THREAD

**Issue by JeremyDrysdale-ibm** [Qiskit/qiskit-metal#325]
### What is the documentation modification?
To prepare for #291, we need a simple notebook that shows how to create:
Lumped Resonator Capacitive (Resonator)

This notebook may already be done, if so please point me in the direction of it so I can verify it's what is needed.
Please put the notebook in the placeholder directory `docs/tut` for now.  You do not need to add the notebook to the docs, I will complete that step as part of #291.

**Comment by priti-ashvin-shah-ibm** [comment]
This is done.
