### ISSUE TITLE
Add function to export variables from qdesign to ansys in class QAnsysRenderer(QRenderer): 

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/qiskit-metal#340]
Please be as descriptive as possible, including: what is expected, why is this feature needed, what is the objective, etc.

### What is the feature being requested?

Add function to export variables from qdesign to ansys in class QAnsysRenderer(QRenderer): 

This already exists in pyEPR, we did it in the tutorials, should be one line of code. Just add for user functionality.

**Comment by priti-ashvin-shah-ibm** [comment]
We are going to focus on pyaedt renderer issues.
