### ISSUE TITLE
design.overwrite_enabled not working when self._name is not provided

### ISSUE THREAD

**Issue by JeremyDrysdale-ibm** [Qiskit/qiskit-metal#35]
From @marcolincs 

### What is the current behavior?
```
design.overwrite_enabled = True
cpw = RouteMeander(design,options=options)
```
run twice gives error: `Pin a of component Q1 is already in use. None has not been built. Please check your pin_input values.`

Reason: the BaseComponent algorithm is assigning a new name at every call. Therefore, the second time around it does not know what to delete before re-drawing.

### Steps to reproduce the problem
```
design.overwrite_enabled = True
cpw = RouteMeander(design,options=options)
cpw = RouteMeander(design,options=options)
```

### What is the expected behavior?
No crash

### Suggested solutions
should the "overwrite_enabled" be generalized to get rid of anything attached to said pins (rather then by name)?

**Comment by JeremyDrysdale-ibm** [comment]
@marcolincs Is this still a bug?  If so, please update 'how to reproduce it'

**Comment by priti-ashvin-shah-ibm** [comment]
closed
