### ISSUE TITLE
Have more default options included for QComponent param entry 

### ISSUE THREAD

**Issue by grace-harper-ibm** [Qiskit/qiskit-metal#404]
### Information

- **Qiskit Metal version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
Param Entry reads in default_options from each QComponent,  but the default_options are so sparsely populated, they are not very useful.

### Steps to reproduce the problem
Create any QComponent 

### What is the expected behavior?
Have more of the parameters auto-filled in for each QComponent.

### Suggested solutions
Consider adding more parameters to each of the default options or consider from template_options.

**Comment by priti-ashvin-shah-ibm** [comment]
This will not be implemented.
