### ISSUE TITLE
Element dropdown bug - large first row

### ISSUE THREAD

**Issue by JeremyDrysdale-ibm** [Qiskit/qiskit-metal#42]
From @zlatko-minev 

### Informations

- **Qiskit Metal version**: all
- **Python version**: all
- **Operating system**: Mac

### What is the current behavior?
In the elements table on mac, the first row seems huge for some reason
![image](https://user-images.githubusercontent.com/68995878/99396635-faf9e100-28af-11eb-8e0e-563ef2166e38.png)

### Steps to reproduce the problem
Click the elements table on a mac

### What is the expected behavior?
Normal sized first row

### Suggested solutions
n/a

**Comment by priti-ashvin-shah-ibm** [comment]
Fixed by @ismirlia.  This can be closed.
