### ISSUE TITLE
Enable github actions linting

### ISSUE THREAD

**Issue by JeremyDrysdale-ibm** [Qiskit/qiskit-metal#420]
Please be as descriptive as possible, including: what is expected, why is this feature needed, what is the objective, etc.

### What is the feature being requested?
Fix linting configuration to allow linting to pass and ignore the long lines we want to keep long

**Comment by priti-ashvin-shah-ibm** [comment]
Some FYI information.
To run pylint, on the command line at top of qiskit-metal.  

`$ pylint qiskit_metal | tee  hold_output.txt`

Metal repo has the .pylint file at
qiskit-metal/.pylint

A good file to compare Metal's pylint to is the pylint with Qiskit Terra.
https://github.com/Qiskit/qiskit-terra/blob/master/.pylintrc

**Comment by priti-ashvin-shah-ibm** [comment]
There is a branch called "linting"

**Comment by JeremyDrysdale-ibm** [comment]
Fixed linting errors in the test module.

**Comment by priti-ashvin-shah-ibm** [comment]
Everything has not been linted, but we have been linting as merging has been happening.
