### ISSUE TITLE
superconducting circuit performance ranking

### ISSUE THREAD

**Issue by leo07010** [Qiskit/qiskit-metal#431]
Please be as descriptive as possible, including: what is expected, why is this feature needed, what is the objective, etc.

### What is the feature being requested?
I have an interesting idea, is it possible to make a superconducting circuit performance ranking LOL

### What are use cases for this feature?
 so that everyone can know which circuits are the best at present，and increase everyone’s participation

**Comment by zlatko-minev** [comment]
I think this is the https://qubitzoo.org/

**Comment by priti-ashvin-shah-ibm** [comment]
Will close since directly relevant to code in this repo.
