### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by leo07010** [Qiskit/qiskit-metal#433]
### Information

- **Qiskit Metal version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-17-4fecc404dbe1> in <module>
----> 1 from .widgets.all_components.table_model_all_components import \
      2     QTableModel_AllComponents

ImportError: attempted relative import with no known parent package

### Steps to reproduce the problem

from .widgets.all_components.table_model_all_components import \
    QTableModel_AllComponents

### What is the expected behavior?

It should pass

### Suggested solutions

giving new file

**Comment by marcolincs** [comment]
@leo07010 , did this case also resolve with the #432 change?
if not, where are you writing the two lines mentioned? We would need to understand how to reproduce it.
....just writing the line in jupyter notebook is expected to fail (python makes relative referencing only work within the package, not from jupyter notebook)

**Comment by leo07010** [comment]
yes,it was also resolved
Thanks
