### ISSUE TITLE
KeyError: 'ANSYSEM_ROOT202' in Sweep_an_option_get_capacitance_matrix

### ISSUE THREAD

**Issue by leo07010** [Qiskit/qiskit-metal#434]
### Information

- **Qiskit Metal version**: 0.0.3
- **Python version**: 3.7.8
- **Operating system**: windows 10

### What is the current behavior?

11:05PM 03s ERROR [open_ansys]: environment variable ANSYSEM_ROOT202 not found. Is Ansys 2020 R2 installed on this machine? If yes, then create said environment variable. If you have a different version of Ansys, then pass to open_ansys() the path to its binary, or the env var that stores it.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-7-1e7f0a68455e> in <module>
      2 # This cell will open the Ansys application.  Run this cell, if Ansys, is not already open.
      3 # A project will be opened using this command.
----> 4 q3d.open_ansys()

c:\users\asus\downloads\qiskit-metal-main\qiskit_metal\renderers\renderer_ansys\ansys_renderer.py in open_ansys(self, path, executable, path_var)
    209         if path is None:
    210             try:
--> 211                 path = os.environ[path_var]
    212             except KeyError:
    213                 self.logger.error(

~\anaconda3\envs\pymetal23\lib\os.py in __getitem__(self, key)
    679         except KeyError:
    680             # raise KeyError with the original key value
--> 681             raise KeyError(key) from None
    682         return self.decodevalue(value)
    683 

KeyError: 'ANSYSEM_ROOT202'

### Steps to reproduce the problem

'q3d =  design.renderers.q3d
# This cell will open the Ansys application.  Run this cell, if Ansys, is not already open.
# A project will be opened using this command.
q3d.open_ansys()'

### What is the expected behavior?

Shouldn't have this problem

**Comment by marcolincs** [comment]
Hi,
Actually yes, this is expected behavior. The message indicate that you need to provide other inputs to this method for it to work.
