### ISSUE TITLE
No module named 'qiskit_metal._gui.widgets.build_history'

### ISSUE THREAD

**Issue by shenzhi-git** [Qiskit/qiskit-metal#437]
### Information

- **Qiskit Metal version**:
 0.03
- **Python version**:
python3.7.2
- **Operating system**:
ubuntu18.04
### What is the current behavior?

![image](https://user-images.githubusercontent.com/40013409/112109181-343eb680-8bec-11eb-80f3-08d426267477.png)

**Comment by JeremyDrysdale-ibm** [comment]
Hi @shenzhi-git, please try the solution that resolved this bug in #432 and let me know if that helps.

**Comment by shenzhi-git** [comment]
I use  virtual environment, and I sucessfully solved the problem.Thanks so much.

**Comment by JeremyDrysdale-ibm** [comment]
No worries, I'm glad it's working for you now.
