### ISSUE TITLE
Renderer options (for 'path') being added to all renderers in qgeom table

### ISSUE THREAD

**Issue by ThomasGM4** [Qiskit/qiskit-metal#439]
### Information

- **Qiskit Metal version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

Renderer option in Ansys is getting added as a GDS option in the qgeometry tables
```

element_table_data = dict(path=dict(wire_bonds=False),
                              junction=dict(
                                  inductance=default_options['Lj'],
                                  capacitance=default_options['Cj'],
                                  resistance=default_options['_Rj'],
                                  mesh_kw_jj=parse_units(
                                      default_options['max_mesh_length_jj'])))
```

### Steps to reproduce the problem

Branch 224_wirebondAnsys

Add any component with paths, then look at design.qgeometry.tables['paths']

### What is the expected behavior?

Should only be adding hfss_wire_bonds and q3d_wire_bonds to the table
![Capture](https://user-images.githubusercontent.com/53087709/112365340-ea1e0980-8cad-11eb-8539-32cc46e5b9d5.PNG)

### Suggested solutions

Suspect it is in the qgeometries_handler, not differentiating the renderers when defining the keys for the tables

**Comment by priti-ashvin-shah-ibm** [comment]
Worked on this so the pull request #224 would have this fix.
