### ISSUE TITLE
Adding the option to invert the gds file when exporting the design

### ISSUE THREAD

**Issue by MAN6O** [Qiskit/qiskit-metal#441]
Please be as descriptive as possible, including: what is expected, why is this feature needed, what is the objective, etc.

### What is the feature being requested?
The option to invert the polygons in the gds chip design, so that the polygons do not describe the metal structures, but the regions of the sc material that needs to be removed during fabrication. 
It can be a checkbox  ([ ] invert design) in the gui export window.

### What are use cases for this feature?
Exporting gds designs and having them inverted saves users the time to edit the code, or do it manually in a GDS-editor.

**Comment by zlatko-minev** [comment]
We should definitely do this. @priti-ashvin-shah-ibm  can help you also if you want to give it a first try shot

**Comment by priti-ashvin-shah-ibm** [comment]
This is being addressed.  In particular - allow for negative mask by selecting the chip and layer.
