### ISSUE TITLE
Add the option to include ground between coupler pads and qubits

### ISSUE THREAD

**Issue by MAN6O** [Qiskit/qiskit-metal#447]
Please be as descriptive as possible, including: what is expected, why is this feature needed, what is the objective, etc.

### What is the feature being requested?
Sometimes it is useful to have the option to include ground between the couplers of qubits and the qubits, right now one has to change the charge line parameters to get something like this which is a restriction.

### What are use cases for this feature?
The ability to create more unique qubit setups and architectures without breaking grounds.

**Comment by zlatko-minev** [comment]
Is there a sketch of what you have in mind? It sounds to me a little like this?
![image](https://user-images.githubusercontent.com/15937254/113243382-c176b080-9267-11eb-9ec5-c45ddc400fd2.png)

from https://qiskit.org/documentation/metal/circuit-examples/index.html

**Comment by MAN6O** [comment]
No, I actually mean it like this:

![image](https://user-images.githubusercontent.com/39159226/114859427-06afec00-9deb-11eb-8fcb-5319c8e4eff1.png)

So that there is ground between the coupling pads and the qubit.

**Comment by priti-ashvin-shah-ibm** [comment]
Please make your own custom component.
