### ISSUE TITLE
Tutorials docs top link broken 

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/qiskit-metal#453]
### What is the documentation modification?

Just noticed that the links at the top dont all work:
Notably when I click tutorials 

![image](https://user-images.githubusercontent.com/15937254/113243262-8b393100-9267-11eb-8c47-8980ec5ad929.png)

**Comment by nonhermitian** [comment]
This is because you need to overload the `layout.html` file used by the theme.  The theme by default is set for the main docs.   It needs to go in the `_templates` folder.

See for example here: https://github.com/Qiskit-Partners/partners/tree/main/docs/_templates

**Comment by JeremyDrysdale-ibm** [comment]
Thanks @nonhermitian I was just emailing you about that!
