### ISSUE TITLE
When sweeping for eigenmode solution matrix, make the design name correspond.

### ISSUE THREAD

**Issue by priti-ashvin-shah-ibm** [Qiskit/qiskit-metal#462]
### Information

- **Qiskit Metal version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
The name of design says "Sweep_Capacitance".

### Steps to reproduce the problem
Run the notebook to use sweep_one_option_get_eigenmode_solution_data.

### What is the expected behavior?
The name of design says "Sweep_Eigenmode".

**Comment by JeremyDrysdale-ibm** [comment]
Closed by PR #463
