### ISSUE TITLE
QLibrary QComponent Creation Error on Windows Server 

### ISSUE THREAD

**Issue by grace-harper-ibm** [Qiskit/qiskit-metal#486]
### Information

- **Qiskit Metal version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
When trying to create a QComponent via Windows Server 
1) Dirtied directories are not cleaned (remain red) even after corresponding QComponent file is rebuilt 
2)  Unable to rebuild QComponents:
```
metal: Reloading component_class_name=TransmonCross; component_module_name=qiskit_metal.qlibrary.qubits.transmon_cross [design_base.reload_and_rebuild_component]
metal: Failed to refresh/rebuild qiskit_metal/qlibrary/qubits/transmon_cross.py due to: 'qiskit_metal.qlibrary.qubits.transmon_cross.TransmonCross' [design_base.reload_and_rebuild_component]
gui0: Rendering element tables to plot window. [mpl_renderer.render]
gui0: Autoscale [plot_window.auto_scale]
```
<img width="767" alt="Screen Shot 2021-04-21 at 5 32 46 PM" src="https://user-images.githubusercontent.com/74260313/115629234-99f39080-a2c7-11eb-8280-a1a17a99ac70.png">

### Steps to reproduce the problem
Enter DeveloperMode and edit a QComponent file. 
When that file shows up red, rebuild and look at gui logs 

### What is the expected behavior?
QComponent rebuilds

**Comment by JeremyDrysdale-ibm** [comment]
Developer mode was discontinued in a few months ago, this bug is no longer relevant.
