### ISSUE TITLE
LOM code updates

### ISSUE THREAD

**Issue by JeremyDrysdale-ibm** [Qiskit/qiskit-metal#488]
Please be as descriptive as possible, including: what is expected, why is this feature needed, what is the objective, etc.

### What is the feature being requested?
New LOM code implementation -- stuff that was done for the paper.

Roughly hacked together already, see Zlatko for rough hacked bits.

After investigating what is needed, please made addition issues as needed in support of this issue.

**Comment by priti-ashvin-shah-ibm** [comment]
@quantum-quant  has implement LOM 2.0 so will close this.
