### ISSUE TITLE
Remove Save

### ISSUE THREAD

**Issue by grace-harper-ibm** [Qiskit/qiskit-metal#493]
### Information

- **Qiskit Metal version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
Remove Save/Load button until #12 is resolved

### Steps to reproduce the problem
Click Save and nothing happens

### What is the expected behavior?
Saving a file that can be read back in

**Comment by JeremyDrysdale-ibm** [comment]
No longer needed
