### ISSUE TITLE
pylint ignore autogenerated

### ISSUE THREAD

**Issue by grace-harper-ibm** [Qiskit/qiskit-metal#501]
### Information

- **Qiskit Metal version**:
- **Python version**:
- **Operating system**:

**Comment by priti-ashvin-shah-ibm** [comment]
@grace-harper-ibm has taken a look at this also, we can work on this together.

**Comment by priti-ashvin-shah-ibm** [comment]
We can add a scroll bar for GDS, HFSS, and Q3D renderers.
