### ISSUE TITLE
Run analysis with pre-saved data

### ISSUE THREAD

**Issue by quantum-quant** [Qiskit/qiskit-metal#507]
Please be as descriptive as possible, including: what is expected, why is this feature needed, what is the objective, etc.

### What is the feature being requested?
Add the capability to run analysis (LOM or EPR) with pre-saved data (capacitance matrix or EPR relevant data) without running Ansys simulations.

### What are use cases for this feature?
Users can run tutorials and specially the analysis portion of code without needing to have access to Ansys

**Comment by JeremyDrysdale-ibm** [comment]
From Yehan: PR #538 partially resolved it and renderer-analysis split is the final solution. So it can be closed
