### ISSUE TITLE
Documentation - the images show rectangle for Josephson Junction in images.

### ISSUE THREAD

**Issue by priti-ashvin-shah-ibm** [Qiskit/qiskit-metal#536]
### Information

- **Qiskit Metal version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
The images in documentation don't show a representation for JJ. 

### What is the expected behavior?
The code has been updated to generate a box, the images, need to be regenerated.

**Comment by JeremyDrysdale-ibm** [comment]
These are missing box for JJ.
https://qiskit.org/documentation/metal/circuit-examples/qubits/02-Transmon_floating.html
https://qiskit.org/documentation/metal/circuit-examples/qubit-couplers/32-TwoTransmonsDirectCoupling.html
https://qiskit.org/documentation/metal/circuit-examples/qubit-couplers/33-TwoTransmonsWithMeander.html
https://qiskit.org/documentation/metal/circuit-examples/input-output-coupling/43-TransmonPocketCL.html
https://qiskit.org/documentation/metal/circuit-examples/small-quantum-chips/51-Four_qubit_chip.html
https://qiskit.org/documentation/metal/circuit-examples/design-flow/Full_Chip_Design_01.html
https://qiskit.org/documentation/metal/circuit-examples/design-flow/Metal_South_Korea_Hackathon_Tutorial.html
https://qiskit.org/documentation/metal/tut/overview/1.1%20High%20Level%20Demo%20of%20Qiskit%20Metal.html
https://qiskit.org/documentation/metal/tut/overview/Deep%20Dive.html
https://qiskit.org/documentation/metal/tut/components/3.1%20QComponent%20Overview.html
https://qiskit.org/documentation/metal/tut/components/3.3%20Creating%20a%20QComponent%20-%20Advanced.html
https://qiskit.org/documentation/metal/tut/analysis/01%20Eigenmode%20and%20EPR.html
https://qiskit.org/documentation/metal/tut/analysis/07%20S%20Param%20Simulation.html
https://qiskit.org/documentation/metal/tut/analysis/08%20Sweep_an_option_get_capacitance_matrix.html
https://qiskit.org/documentation/metal/tut/renderers/GDS%20QRenderer.html

Hard to know if the JJ was drawn.  The  axis is covering where the JJ:
https://qiskit.org/documentation/metal/tut/analysis/03%20Capacitance%20and%20LOM.html
https://qiskit.org/documentation/metal/tut/analysis/04%20Analyzing%20a%20transmon.html.
https://qiskit.org/documentation/metal/tut/analysis/05%20Analyzing%20a%20transmon%20and%20a%20resonator.html
