### ISSUE TITLE
C related errors when instantiating GUI in non-interactive Python

### ISSUE THREAD

**Issue by JeremyDrysdale-ibm** [Qiskit/qiskit-metal#54]
### Informations

- **Qiskit Metal version**: 0.0.1
- **Python version**: 3.8.3
- **Operating system**: Mac

From @coruscating 

### What is the current behavior?
I get errors when starting metal in python scripts on the command line. Here's a barebones script that works fine in Jupyter, but causes either `Illegal Instruction: 4`, `Segmentation fault: 11`, or just crashes when run:

```
import qiskit_metal as metal
from qiskit_metal import designs, draw
from qiskit_metal import MetalGUI, Dict, Headings

design = designs.DesignPlanar()
gui = MetalGUI(design)
gui.rebuild()
gui.autoscale()
```

When the code is run, the GUI sometimes appears with this annoying prompt (doesn't matter which option you choose, it crashes either way):
![image](https://user-images.githubusercontent.com/68995878/99410482-89765e80-28c0-11eb-8850-552b860b5917.png)

### Steps to reproduce the problem
```
import qiskit_metal as metal
from qiskit_metal import designs, draw
from qiskit_metal import MetalGUI, Dict, Headings

design = designs.DesignPlanar()
gui = MetalGUI(design)
gui.rebuild()
gui.autoscale()
```

### What is the expected behavior?
No crash, or graceful handling of teh error

### Suggested solutions
n/a

**Comment by JeremyDrysdale-ibm** [comment]
@priti-ashvin-shah-ibm I don't have a mac so I can't check this, can you please try to reproduce this and comment if you can?

**Comment by priti-ashvin-shah-ibm** [comment]
@JeremyDrysdale-ibm,  I tried to re-create few times, and was not able to.

**Comment by JeremyDrysdale-ibm** [comment]
This appears to have been resolved, but the issue never closed.
