### ISSUE TITLE
Add Ansys COM verification check in the Ansys-renderer initialize method

### ISSUE THREAD

**Issue by marcolincs** [Qiskit/qiskit-metal#546]
### What is the feature being requested?

Insert Ansys "proper installation" check in the Ansys renderer code (in the "initialization" method)

### What are use cases for this feature?

for Ansys2020R2 this would be the command to test that Ansys is properly installed: `win32com.client.Dispatch('AnsoftHfss.HfssScriptInterface')`.....there might be a better command that does not actually "execute" anything. Also the COM key might be different for different versions of Ansys, so will need to check other possible keys in the loop.

Also add this to the FAQ in case something goes wrong in a different way

**Comment by priti-ashvin-shah-ibm** [comment]
This will become sunset with pyaedt renderer.
