### ISSUE TITLE
Add any missing components to the Circuit Library docs

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/qiskit-metal#548]
### What is the documentation modification?

Add any missing components to the Circuit Library docs

![image](https://user-images.githubusercontent.com/15937254/120380496-3fe6e180-c2ef-11eb-800c-18768e5b7979.png)

such as transmon_pocket_cl is not in there. Let's add all the available components 
![image](https://user-images.githubusercontent.com/15937254/120380572-555c0b80-c2ef-11eb-84c3-9744e7568562.png)

**Comment by zlatko-minev** [comment]
@JeremyDrysdale-ibm   perhaps for Sagarika when she add her new qubit design or a good test project for the interns, @ThomasGM4  @marcolincs  to create and test all the components and add them in here?
![image](https://user-images.githubusercontent.com/15937254/120380725-863c4080-c2ef-11eb-8487-93e9721dc0ef.png)

**Comment by ThomasGM4** [comment]
Do we want all components covered, just primary parents (eg. transmon with flux line another separate or just transmon pocket), or just basic subset of common components used?
