### ISSUE TITLE
MetaGUI closes even when choosing cancel

### ISSUE THREAD

**Issue by grace-harper-ibm** [Qiskit/qiskit-metal#565]
### Information

- **Qiskit Metal version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
<img width="869" alt="Screen Shot 2021-06-07 at 10 15 28 PM" src="https://user-images.githubusercontent.com/74260313/121117517-df1f4380-c7dd-11eb-8643-2256117d5169.png">

Regardless of which option is chosen, the GUI will close the UI but stay running in the background.

### Steps to reproduce the problem
Click the exit button on MetalGUI and choose any option

### What is the expected behavior?
"Cancel" should take the user back to the GUI without changes. "Yes" should save and close. "No" should not save and still close.

**Comment by JeremyDrysdale-ibm** [comment]
Resolved as part of PR #666
