### ISSUE TITLE
QGeometry Handler Database

### ISSUE THREAD

**Issue by JeremyDrysdale-ibm** [Qiskit/qiskit-metal#58]
### What is the feature being requested?
Implement QGeometry Handler Database
- Define backup/recovery strategy
- Define data retention strategy
- Define data destruction strategy
- Define interfaces
- Implement interfaces
- Implement additional strategies described above

### What are use cases for this feature?
n/a

**Comment by priti-ashvin-shah-ibm** [comment]
No one is planning to port to a database.
