### ISSUE TITLE
Cannot autogenerate gui from .ui files if creating conda env from most recent instructions

### ISSUE THREAD

**Issue by grace-harper-ibm** [Qiskit/qiskit-metal#583]
### Information

- **Qiskit Metal version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
If I use an old conda env when running ./__compile_ui_to_py.shell , then the _ui.py files are generated from the .ui files as expected, with external imports and retranslations

However, if I make a new conda env by following the instructions in the READMe and then run ./__compile_ui_to_py.shell the generated _ui.py will be missing necessary imports (such as `from .widgets.qlibrary_display.tree_view_qlibrary import TreeViewQLibrary`) and will not have a retranslations

### Steps to reproduce the problem
Create a new conda env and run  ./__compile_ui_to_py.shell 

### What is the expected behavior?
 ./__compile_ui_to_py.shell  should generated usable _ui.py files 

### Suggested solutions
Perhaps certain libraries we use have been upgraded without our knowledge

**Comment by priti-ashvin-shah-ibm** [comment]
The conda env has been updated many times.  This can be closed.
