### ISSUE TITLE
Impedance & S analysis: Add fitting routine for resonance

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/qiskit-metal#584]
Please be as descriptive as possible, including: what is expected, why is this feature needed, what is the objective, etc.

### What is the feature being requested?

Add a procedure to fit for a scattering curve S21 (complex), as discussed say here  https://arxiv.org/pdf/2106.06173.pdf

![image](https://user-images.githubusercontent.com/15937254/122220352-3f695180-ce7e-11eb-8b38-f99b50460e31.png)

**Comment by JoshDumo** [comment]
Hello! I'm a new contributor but I'd like to try this one if that's ok.
Khalil et.al. https://arxiv.org/abs/1108.3117 have a kind of similar discussion on microwave resonators, and lmfit uses their equation in a tutorial on fitting a complex resonator model https://lmfit.github.io/lmfit-py/examples/example_complex_resonator_model.html.
We could adapt that approach to fit eq 45?

**Comment by zlatko-minev** [comment]
Hi Josh, 

This is great to hear. Yes, happy to have you contribute and you can even because an author on Metal with contributions. 

Feel free to reach out on Slack in #metal channel if you run into issues. 

Also relevant discussion may be https://qiskit.slack.com/archives/C01R8KP5WP7/p1626283484499800

**Comment by marcolincs** [comment]
Hi @JoshDumo , how is this one going? Did you have any bandwidth to work on it?

**Comment by JoshDumo** [comment]
Hi @marcolincs 
I have a done a little bit but so far not so good. 

Please have a look at some notebooks I have worked on so far,[ here in my github repository](https://github.com/JoshDumo/QMetal-ResonanceFitting)

As you'll see, the fitting doesn't work great just yet. 

If you have any insights, I am very happy to hear them.

**Comment by SamarthH** [comment]
Hi @JoshDumo 
Do you mind if I also try my hand at this? I have done this thing in C (https://github.com/SamarthH/phiRM-DCM). I think that I might be able to help here. If you want to work on this, you might want to look at appendix E of Jiansong Gao's thesis (the person who in my knowledge first described the phiRM)

**Comment by JoshDumo** [comment]
Yes, need a hand. Please go ahead.

**Comment by zlatko-minev** [comment]
Awesome, you can post questions and updates here

**Comment by SamarthH** [comment]
@zlatko-minev : I have implemented the methodology in pull request #737 . I have tested it with the output of Tutorial 4.16. Please let me know if any changes are necessary

**Comment by zlatko-minev** [comment]
Great work!! We will look it over and commnet!

**Comment by SamarthH** [comment]
Hi. Is there any further work left on this?

**Comment by priti-ashvin-shah-ibm** [comment]
Looks like work has merged.  Will close this issue.
