### ISSUE TITLE
Streamlining notebooks

### ISSUE THREAD

**Issue by marcolincs** [Qiskit/qiskit-metal#585]
### What is the documentation modification?

Expanding on the #575 effort:
- [ ] scrub the content of the notebooks. Remove redundancy and focus the topics to the notebook titles
- [ ] create new notebook as needed for the flow (move to other notebooks the content that does not match the title
- [ ] add references to the videos if/as appropriate

**Comment by zlatko-minev** [comment]
Is this done>

**Comment by marcolincs** [comment]
no

**Comment by priti-ashvin-shah-ibm** [comment]
On going effort.  Not a separate project to work on.
