### ISSUE TITLE
Redesign design.element.tables

### ISSUE THREAD

**Issue by JeremyDrysdale-ibm** [Qiskit/qiskit-metal#59]
### What is the feature being requested?
Redesign design.element.tables
Related to #58 

From Zlatko:
GeoPandas seems to handle what we need with shapely to manipulate shapely data in pandas
https://geopandas.org/data_structures.html

### What are use cases for this feature?
Redesign for speed and enhanced usability

**Comment by priti-ashvin-shah-ibm** [comment]
There are no users requesting more speed here.  For now, we can close this issue.
