### ISSUE TITLE
Adding all available excitation/boundary conditions in Ansys

### ISSUE THREAD

**Issue by ambhudia** [Qiskit/qiskit-metal#618]
Please be as descriptive as possible, including: what is expected, why is this feature needed, what is the objective, etc.

### What is the feature being requested?
It would be useful to be able to add different boundary conditions other than PerfE e.g. impedance, and different excitation methods

### What are use cases for this feature?
In the analysis of kinetic inductance, for instance

**Comment by priti-ashvin-shah-ibm** [comment]
pyaedt renderer for Ansys can address this later when released.
