### ISSUE TITLE
One tool, one renderer

### ISSUE THREAD

**Issue by marcolincs** [Qiskit/qiskit-metal#645]
Follow-up from #495

### What is the feature being requested?

desire to keep hfss and q3d rendering methods separate, but to only have one single Ansys renderer (instead of current two renderers). The key to solve this might be to have hfss and q3d methods as composed in the ansys renderer class, and instantiate them as needed

### What are use cases for this feature?

Use simplification and centralizing com ports and other renderer-related operations.

**Comment by priti-ashvin-shah-ibm** [comment]
The pyaedt renderer has a different class for q3d,DM, EM.  So, this logic would not apply to new renderers for Ansys.
