### ISSUE TITLE
Remove pinfo from QAnalysis 

### ISSUE THREAD

**Issue by marcolincs** [Qiskit/qiskit-metal#646]
### What is the feature being requested?

Remove the dependency of QAnalysis cub-classes from pinfo, to improve the "split" from renderers logic

### What are use cases for this feature?

Modularization for independent use of analysis

**Comment by priti-ashvin-shah-ibm** [comment]
We  are replacing Ansys windows com renderer with pyadet based renderer. This issue can be closed since the Ansys windows renderer will be sunset.
