### ISSUE TITLE
Make QAnalysis (and QSimulation) objects usable without a design

### ISSUE THREAD

**Issue by marcolincs** [Qiskit/qiskit-metal#647]
### What is the feature being requested?

Follows #631 and #642
we cannot assume that analysis is used on a design or that it will use a renderer. So it needs to be made optional

### What are use cases for this feature?

Modularization for independent use of analysis

**Comment by priti-ashvin-shah-ibm** [comment]
LOM is stand alone, and EPR will soon be stand alone. We can close this.
