### ISSUE TITLE
Add icons for all the tutorials that are missing one

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/qiskit-metal#655]
### What is the documentation modification?

Add icons for all the tutorials that are missing one

![image](https://user-images.githubusercontent.com/15937254/127211472-0837e145-7e2a-49ff-ab91-ab7148065c17.png)

![image](https://user-images.githubusercontent.com/15937254/127211457-6dbf4693-1668-4201-b07b-1d8d3a3aaee8.png)
![image](https://user-images.githubusercontent.com/15937254/127211489-9fa09c52-2c3f-4486-8715-5c233dc728cf.png)

**Comment by JeremyDrysdale-ibm** [comment]
None of these have graphical output.  The cards require graphical output otherwise it will use the default qiskit logo.  The exception is 4.14 which doesn't execute due to a bug that will be corrected in #648.

**Comment by zlatko-minev** [comment]
Nice. We can use some of the visual from them or icons. For example, for the transmon analytics we can use some of the resulting plots from nicks notebook or just a schematic image of the transmon. 

For wavefunction for example we can show one of the images of a wavefunction etc.
