### ISSUE TITLE
Incorrectly copied comments

### ISSUE THREAD

**Issue by zachparrott** [Qiskit/qiskit-metal#668]
### Information

- **Qiskit Metal version**: 0.0.4
- **Python version**: n/a
- **Operating system**: n/a

### What is the current behavior?
The comments for the **run** method in qiskit_metal.analyses.quantization.energy_participation_ratio.py are incorrectly copied from the **run** method of qiskit_metal.analyses.quantization.lumped_oscillator_model.py. 

### Steps to reproduce the problem
https://github.com/Qiskit/qiskit-metal/blob/e5cbb6559ed650cbb75e696322ccc7a918d9c5a9/qiskit_metal/analyses/quantization/energy_participation_ratio.py#L148-L157

https://github.com/Qiskit/qiskit-metal/blob/e5cbb6559ed650cbb75e696322ccc7a918d9c5a9/qiskit_metal/analyses/quantization/lumped_oscillator_model.py#L119-L130

### What is the expected behavior?
Applicable description of the inputs and returns for EPR's run and not the LOM's run method.

### Suggested solutions
Relevant comments.

**Comment by zlatko-minev** [comment]
Thanks, @zachparrott , for nothing this!
