### ISSUE TITLE
Pin position and direction utilities

### ISSUE THREAD

**Issue by JeremyDrysdale-ibm** [Qiskit/qiskit-metal#67]
From @marcolincs 

### What is the feature being requested?
It would be good to not have to repeat the extraction code for position and direction from pins and have a universal method. For now there exists a `seed_from_pin()` method in the QRoute class, so that I could centralize this operation.
We could take the `seed_from_pin()` and make of it a method of base components, that accepts the pin name as input and returns position and direction. <- this is preferable, no need to transform pin into class.
Alternative we transform pin to class and get the method in it

### What are use cases for this feature?
n/a

**Comment by priti-ashvin-shah-ibm** [comment]
There is an established convention with user community.
