### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by lyyangtian** [Qiskit/qiskit-metal#697]
### Information

- **Qiskit Metal version**:0.0.4
- **Python version**:3.9
- **Operating system**:win 10

### What is the current behavior?

I can't find qiskit_metal.qlibrary.connectors in 0.0.4

### Steps to reproduce the problem

from qiskit_metal.qlibrary.connectors.cpw_finger_cap import CPWFingerCap
is error

### What is the expected behavior?

I want to import CPWFingerCap

### Suggested solutions

Where can I find qiskit_metal.qlibrary.connectors's files in 0.0.4?  Thank you!

**Comment by ThomasGM4** [comment]
The qlibrary has been updated to a new structure, please check the files and make sure are up to date with your version of the main branch.

You will probably find what you are looking for in qiskit_metal.qlibrary.lumped
