### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by lyyangtian** [Qiskit/qiskit-metal#698]
### Information

- **Qiskit Metal version**:0.0.4
- **Python version**:3.9
- **Operating system**:win 10

### What is the current behavior?

I can't find qiskit_metal.qlibrary.connectors in 0.0.4

### Steps to reproduce the problem

from qiskit_metal.qlibrary.connectors.cpw_finger_cap import CPWFingerCap
is error

### What is the expected behavior?

I want to import CPWFingerCap

### Suggested solutions
Where can I find qiskit_metal.qlibrary.connectors's files in 0.0.4?  Thank you!

**Comment by ThomasGM4** [comment]
Duplicate issue
