### ISSUE TITLE
rewrite QDesign rebuild function for speed

### ISSUE THREAD

**Issue by JeremyDrysdale-ibm** [Qiskit/qiskit-metal#72]
From @smukesh25 

### What is the feature being requested?
qdesign.rebuild() function needs to be re-written to be faster

### What are use cases for this feature?
rewrite for speed

**Comment by priti-ashvin-shah-ibm** [comment]
To implement this, some assumptions need to be made so some components are not rebuilt. For now, our users are used to rebuilding all of the design.
