### ISSUE TITLE
When making a positive mask, the junction is being placed twice. 

### ISSUE THREAD

**Issue by priti-ashvin-shah-ibm** [Qiskit/qiskit-metal#723]
### Information

- **Qiskit Metal version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
When creating a negative mask, the gds file has just one junction as desired
When creating a positive mask,  the gds file has junction on (datatype 53 and 54) and layer 1

### What is the expected behavior?

Only one junction on datatype 53 and 54.

### Suggested solutions
Investigate making of keep-out (nocheese) region.  Don't need the junction to calculate the keep-out region.

**Comment by ThomasGM4** [comment]
Did this not get resolved in your recent PR?

**Comment by priti-ashvin-shah-ibm** [comment]
This should been resolved when merged.
