### ISSUE TITLE
Typo - the two notebooks need to be updated. 

### ISSUE THREAD

**Issue by priti-ashvin-shah-ibm** [Qiskit/qiskit-metal#733]
### Information

- **Qiskit Metal version**:
- **Python version**:
- **Operating system**:

Conversation in slack at #metal. 
https://qiskit.slack.com/archives/C01R8KP5WP7/p1638275287214400

### What is the current behavior?
It appears that size_x should be ‘9mm’ in the two notebooks.  The notebook in tut directory needs to be run and saved.

https://qiskit.org/documentation/metal/tut/2-From-components-to-chip/2.21-Design-a-4-qubit-full-chip.html#Let%E2%80%99s-design-the-core-of-the-chip

and
the cell has to be updated here. 

https://github.com/Qiskit/qiskit-metal/blob/main/tutorials/2%20From%20components%2[…]chip%20design/2.21%20Design%20a%204%20qubit%20full%20chip.ipynb

**Comment by Carlosbogo** [comment]
Hi, I would like to work on this. Is there anyone doing it already?

**Comment by priti-ashvin-shah-ibm** [comment]
No, please feel free go ahead  and do this. 

Thanks for contributing to Metal.

**Comment by priti-ashvin-shah-ibm** [comment]
https://github.com/Qiskit/qiskit-metal/blob/main/CONTRIBUTING.md

@Carlosbogo , the above links should help you.  It explains the  CLA.

**Comment by Arch0125** [comment]
@priti-ashvin-shah-ibm 
Hi, I would like to work on this issue.
Is this the intended change ?
![Screenshot from 2021-12-06 22-29-15](https://user-images.githubusercontent.com/72722967/144888976-fbcac92f-65e4-4a46-b37b-0bf9ce4fc452.png)

**Comment by priti-ashvin-shah-ibm** [comment]
@Arch0125 , yes.  Please do follow the rest of the work needed to confirm nothing else has been affected.  

```
It appears that size_x should be ‘9mm’ in the two notebooks. The notebook in tut directory needs to be run and saved.

https://qiskit.org/documentation/metal/tut/2-From-components-to-chip/2.21-Design-a-4-qubit-full-chip.html#Let%E2%80%99s-design-the-core-of-the-chip

and
the cell has to be updated here.

https://github.com/Qiskit/qiskit-metal/blob/main/tutorials/2%20From%20components%2[…]chip%20design/2.21%20Design%20a%204%20qubit%20full%20chip.ipynb
```

**Comment by Arch0125** [comment]
Yes I will start working on it.

**Comment by Arch0125** [comment]
The cell link (https://github.com/Qiskit/qiskit-metal/blob/main/tutorials/2%20From%20components%2[…]chip%20design/2.21%20Design%20a%204%20qubit%20full%20chip.ipynb) is throwing server error 500 maybe because the qiskit-metal/blob directory is non-existent

**Comment by priti-ashvin-shah-ibm** [comment]
> The cell link ([https://github.com/Qiskit/qiskit-metal/blob/main/tutorials/2%20From%20components%2[…]chip%20design/2.21%20Design%20a%204%20qubit%20full%20chip.ipynb](https://github.com/Qiskit/qiskit-metal/blob/main/tutorials/2%20From%20components%2%5B%E2%80%A6%5Dchip%20design/2.21%20Design%20a%204%20qubit%20full%20chip.ipynb)) is throwing server error 500 maybe because the qiskit-metal/blob directory is non-existent

https://github.com/Qiskit/qiskit-metal/blob/main/tutorials/Appendix%20A%20Full%20design%20flow%20examples/Example%20full%20chip%20design.ipynb



This should be similar to the notebook in the doc/tut path.  The idea is that all the tutorial notebooks are in 
/tutorial directory have been run so the users can see the expected output.  Significant tutorials are in the doc/tut directories.  The idea is to confirm the tutorial notebook in /tutorial directory matches the notebook in /docs/tut.  If they are off, they need to be updated to similar.  

The notebooks in /tutorial  represent the complete set of tutorials.  The notebooks in /tutorial directory are typically not execute.

**Comment by bopardikarsoham** [comment]
I've submitted a PR for this issue  @priti-ashvin-shah-ibm.

**Comment by priti-ashvin-shah-ibm** [comment]
Merged, but issue not closed.
