### ISSUE TITLE
Rewrite QDesign.all_component_names_id for speed

### ISSUE THREAD

**Issue by JeremyDrysdale-ibm** [Qiskit/qiskit-metal#74]
From @priti-ashvin-shah-ibm 

### What is the feature being requested?
Rewrite QDesign.all_component_names_id for speed

### What are use cases for this feature?
Enhanced usability

**Comment by priti-ashvin-shah-ibm** [comment]
No user has expressed urgency for this.  We will close this until there is user impact.
