### ISSUE TITLE
Pull Requests are not passing run_all_tests.

### ISSUE THREAD

**Issue by priti-ashvin-shah-ibm** [Qiskit/qiskit-metal#750]
### Information

- **Qiskit Metal version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
All the pull requests are failing the self tests.

**Comment by bowmanconnor** [comment]
Hi @priti-ashvin-shah-ibm, 

Has this issue been resolved? If so would you mind closing the issue?
