### ISSUE TITLE
Fillet is not happening anymore.

### ISSUE THREAD

**Issue by priti-ashvin-shah-ibm** [Qiskit/qiskit-metal#782]
### Information

- **Qiskit Metal version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
After gui.rebuild, the cpws are not fillet'd.

### Steps to reproduce the problem
Run notebook 2.21

### What is the expected behavior?
The cpws should be fillet'd in the GUI.

**Comment by ThomasGM4** [comment]
PR 783 fixed this right?

**Comment by priti-ashvin-shah-ibm** [comment]
Yes, there is a merged icon on the issue too.
