### ISSUE TITLE
Fix component name in Metal GUI

### ISSUE THREAD

**Issue by na13neil** [Qiskit/qiskit-metal#809]
### Information
Name of the component is "Transmon Pocket Connector Lines". It should be replaced with "Transmon Pocket Charge Line".

![Screenshot (83)](https://user-images.githubusercontent.com/34724132/178164201-5e2c528c-daa0-4ae1-9e0f-a30972053b14.png)
- **Qiskit Metal version**: 0.1.0
- **Python version**: 3.9
- **Operating system**: Windows 10

### What is the current behavior?
Component name is wrong in Metal GUI

### Steps to reproduce the problem
Launch Metal GUI; click on library and see the component.

### What is the expected behavior?
To display correct name.

### Suggested solutions
Correct the name.

**Comment by AbeerVaishnav13** [comment]
Pull request related to the issue was merged successfully. Closing the issue.
