### ISSUE TITLE
Pre-Commit Hook

### ISSUE THREAD

**Issue by cdelnano** [Qiskit/qiskit-metal#874]
### Information

- **Qiskit Metal version**: Latest as of 11/8
- **Python version**: 3.1
- **Operating system**: Mac

### What is the current behavior?
The pre-commit hook looks at BOTH .py and .ipynb files.

### Steps to reproduce the problem
I tried to delete a .ipynb file that was no longer needed, and the yapf formatting raised an error when I tried to commit this change.

### What is the expected behavior?
The pre-commit hook should only look at .py files, not .ipynb files.

### Suggested solutions
Modify the pre-commit hook so that it only looks at .py files, not .ipynb files.

**Comment by priti-ashvin-shah-ibm** [comment]
Merged, should be closed.
