### ISSUE TITLE
Layout versus schematic (LVS)

### ISSUE THREAD

**Issue by joamatab** [Qiskit/qiskit-metal#878]
As circuits become more complex is important to check that your design intent matches the produced layout

![image](https://user-images.githubusercontent.com/4514346/204631086-80ea66f5-763a-45e6-8553-d548edd742d3.png)

What are your plans for LVS?

We just added schematic driven layout in [gdsfactory](https://gdsfactory.github.io/gdsfactory/README.html) and netlist extraction and we were wondering the best way to compare both. See [issue](https://github.com/gdsfactory/gdsfactory/issues/934)

i was wondering if this is something that you also plan on implementing in qiskit-metal

**Comment by priti-ashvin-shah-ibm** [comment]
We welcome the the community to add features to our open-source repository. This is an open ended question, will close for now.
