### ISSUE TITLE
File naming: utils vs utility_functions

### ISSUE THREAD

**Issue by JeremyDrysdale-ibm** [Qiskit/qiskit-metal#88]
From @lcapelluto 

### What is the feature being requested?
`utility_functions.py`: In every other project, I've always seen these called just `utils.py` or `util.py`. Not sure how much this is common practice vs convention. Should be a low cost to update

### What are use cases for this feature?
n/a

**Comment by priti-ashvin-shah-ibm** [comment]
No user impact for this.  Will close for now.
