### ISSUE TITLE
mitre limit in conda environment causing CI to fail

### ISSUE THREAD

**Issue by cdelnano** [Qiskit/qiskit-metal#885]
### Information

- **Qiskit Metal version**: 
- **Python version**: 3.10.8
- **Operating system**: Mac

### What is the current behavior?
conda environment producing a value that is < .02 different from expected value produced in virtualenv

### Steps to reproduce the problem
Run run_all_tests.py with conda environment

### What is the expected behavior?
CI will pass

### Suggested solutions
Comment out poly5 variable in test_draw.py with mitre limit until chosen environment is put into ReadMe and Github actions.

**Comment by priti-ashvin-shah-ibm** [comment]
Merged, so will close this.
