### ISSUE TITLE
CI Pipeline Needs to Run Testing on Windows

### ISSUE THREAD

**Issue by cdelnano** [Qiskit/qiskit-metal#901]
### Information

- **Qiskit Metal version**:
- **Python version**: 3.10
- **Operating system**: Windows

### What is the current behavior?
CI pipeline excludes testing on Windows

### Steps to reproduce the problem
Github actions has this commented out

### What is the expected behavior?
We should be running CI on all operating systems

### Suggested solutions
Uncomment the code in Github actions that runs this testing on Windows

**Comment by priti-ashvin-shah-ibm** [comment]
Since code merged, we can close this issue.
