### ISSUE TITLE
cpw_gap bug in rendering qiskit-metal design to GDS file.

### ISSUE THREAD

**Issue by patrick612** [Qiskit/qiskit-metal#922]
### Information

- **Qiskit Metal version**: 0.0.4
- **Python version**: 3.9.12
- **Operating system**: Windows 11

### What is the current behavior?
The cpw_gap does not render correctly when exported to GDS. Specifically, although the fillet of the trace is there, cpw_gap has no fillet and has square edges. Furthermore, the width of cpw_gap seems to have doubled when rendered on GDS.

### Steps to reproduce the problem
Make any circuits with cpw or any elements with etched gap, then export the qiskit-metal design to a GDS file.

### What is the expected behavior?
It is expected to see the fillet and correct width on etched gap of design elements like cpw.

### EDIT:
I have tried using the updated version of qiskit-metal(0.1.2) to see if the above issue is resolved. The code I used to replicate the issue was taken from a "Simple CPW Meander" example given in the link: https://qiskit.org/documentation/metal/circuit-examples/B.Resonators/11-Resonator_Meander.html
code:
<img width="1091" alt="Screen Shot 2023-03-02 at 1 08 06 PM" src="https://user-images.githubusercontent.com/77427280/222515766-c661d68a-1d85-4426-b3e3-bd55378a0687.png">

The code gives me the following rendered image on GUI:
<img width="914" alt="Screen Shot 2023-03-02 at 1 04 22 PM" src="https://user-images.githubusercontent.com/77427280/222516041-6f6a39dd-fd8b-4feb-a7a5-4073d354a59a.png">

When I exported this design to GDS, I used set of default options:
<img width="463" alt="Screen Shot 2023-03-02 at 1 07 24 PM" src="https://user-images.githubusercontent.com/77427280/222516161-50ee2591-1cba-40ba-a479-802924e6e967.png">

But after exporting to GDS, the design looks like:
<img width="764" alt="Screen Shot 2023-03-02 at 1 04 06 PM" src="https://user-images.githubusercontent.com/77427280/222516299-a0bc943d-cc2c-4e67-a3bb-5f9146d9aa0f.png">

The grey cpw_gap of cpw_meander still renders as sharp edged box on GDS. Updating the qiskit-metal module does not seem to resolve this issue

**Comment by priti-ashvin-shah-ibm** [comment]
If that doesn't work, can you copy/paste the code you used?   To duplicate your situation. I don't want to re-type your code.

**Comment by patrick612** [comment]
Changing the view_in_file to False in the no_cheese options worked!! Thank you!

**Comment by priti-ashvin-shah-ibm** [comment]
Super.  I will close this issue.
