### ISSUE TITLE
Pyside2 version causing failure to create conda env

### ISSUE THREAD

**Issue by cdelnano** [Qiskit/qiskit-metal#924]
### Information

- **Qiskit Metal version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
pyside2==5.15.2.1 is causing an error when trying to create a conda env

### Steps to reproduce the problem
tried to create conda env

### What is the expected behavior?
no failure to arise

### Suggested solutions
I specified the version of pyside2 to install in environment.yml

**Comment by obrienpja** [comment]
Thanks for finding this @cdelnano !
