### ISSUE TITLE
Renaming Components and Build Order

### ISSUE THREAD

**Issue by JeremyDrysdale-ibm** [Qiskit/qiskit-metal#94]
### Information

- **Qiskit Metal version**: all
- **Python version**: all
- **Operating system**: all

### What is the current behavior?
If we choose to rename the key of a component such as a Qubit, the key, value pair automatically gets moved to the end of the dictionary. This can cause disruptions in dependencies such as building the CPW before the transmon

### Steps to reproduce the problem
Create some components, rename one, notice the order changes

### What is the expected behavior?
The order does not change -- update occurs in place.

**Comment by priti-ashvin-shah-ibm** [comment]
This is so integrated into the order of rebuild.  The workaround is to save the order in a Jupyter notebook or script.
